#!/bin/bash

# cleanup old build files
F=README.md; [ ! -f ./$F ] || rm $F 
F=01_TOC.md; [ ! -f ./$F ] || rm $F 

# generate TOC
pandoc -s -f gfm -t markdown --toc --data-dir=. --template toc-only *.md > 01_TOC.md

# concat all MD files into README.md
pandoc -f gfm -t gfm --data-dir=. --strip-comments *.md > README.md
